// Shared genre catalogue — used by onboarding (GenrePreferences) and profile
// editing. PRD § Functional Requirements > Profile setup: predefined list.
export const GENRES = [
  "Fiction",
  "Fantasy",
  "Science fiction",
  "Mystery",
  "Thriller",
  "Romance",
  "Horror",
  "Historical fiction",
  "Literary fiction",
  "Young Adult (YA)",
  "Children's Books",
  "Classics",
  "Biography & Memoir",
  "History",
  "Self-Help",
  "Business & Finance",
  "Psychology",
  "Health & Wellness",
  "Religion & Spirituality",
  "Politics",
  "True Crime",
  "Science",
  "African Literature",
  "Nigerian Literature",
  "Poetry",
] as const;
